# Лабораторная работа №1
## Выполнила студентка группы БФИ1901 Балагурова Диана Николаевна
### Задание №1
Описание условия задания

In [4]:
print("Hello, World!")

Hello, World!


In [49]:
from datetime import datetime
import time

# задание 1

m = 50
n = 50
min_limit = -250
max_limit = 1002
m = int(input())
n = int(input())
min_lim = int(input())
max_lim = int(input())
a = [[np.random.randint(min_lim, max_lim) for j in range(m)] for i in range(n)]
matr = np.array(a)
print(matr)

# задание 2

# стандартная функция сортировки

start_time = datetime.now()
vybor = matr.copy()
for i in range(n):
    vybor[i].sort()
    print(vybor[i])
print(datetime.now() - start_time)

# Выбором 

start_time = datetime.now()
vybor = matr.copy()
def sel_sort(array):
    for i in range(len(array) - 1):
        m = i
        j = i + 1
        while j < len(array):
            if array[j] < array[m]:
                m = j
            j = j + 1
        array[i], array[m] = array[m], array[i]
for i in range(n):
    sel_sort(vybor[i])
    print(vybor[i])
print(datetime.now() - start_time)

# Вставкой 

start_time = datetime.now()
vstav = matr.copy()
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i-1
        while j >=0 and key < arr[j] :
            arr[j+1] = arr[j]
            j -= 1
        arr[j+1] = key 
for i in range(n):
    sel_sort(vstav[i])
    print(vstav[i])
print(datetime.now() - start_time)
        
# Обменом 

start_time = datetime.now()
obmen = matr.copy()
def bubble(array):
    for i in range(m-1):
        for j in range(m-i-1):
            if array[j] > array[j+1]:
                buff = array[j]
                array[j] = array[j+1]
                array[j+1] = buff
for i in range(n):
    bubble(obmen[i])
    print(obmen[i])
print(datetime.now() - start_time)

# Шелла 

start_time = datetime.now()
shell = matr.copy()
def shella(data):
    inc = len(data) // 2
    while inc:
        for i, el in enumerate(data):
            while i >= inc and data[i - inc] > el:
                data[i] = data[i - inc]
                i -= inc
            data[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
    return data
for i in range(n):
    shella(shell[i])
    print(shell[i])
print(datetime.now() - start_time)

# Турнирная 
# Быстрая сортировка 

start_time = datetime.now()
fast = matr.copy()
def partition(array, begin, end):
    pivot = begin
    for i in range(begin+1, end+1):
        if array[i] <= array[begin]:
            pivot += 1
            array[i], array[pivot] = array[pivot], array[i]
    array[pivot], array[begin] = array[begin], array[pivot]
    return pivot
def quick_sort(array, begin=0, end=None):
    if end is None:
        end = len(array) - 1
    
    def _quicksort(array, begin, end):
        if begin >= end:
            return
        pivot = partition(array, begin, end)
        _quicksort(array, begin, pivot-1)
        _quicksort(array, pivot+1, end)
    return _quicksort(array, begin, end)
for i in range(n):
    quick_sort(fast[i])
    print(fast[i])
print(datetime.now() - start_time)

# Пирамидальная


10
10
0
10
[[4 8 1 5 8 2 2 5 3 4]
 [3 6 4 0 9 1 5 7 5 6]
 [9 1 1 6 3 5 8 1 0 3]
 [3 0 7 4 0 2 2 2 2 1]
 [0 2 1 8 8 5 9 3 9 0]
 [6 9 5 7 0 8 1 1 3 2]
 [1 7 4 9 2 9 3 6 9 0]
 [0 4 6 8 7 3 1 6 2 6]
 [1 7 5 6 1 8 1 5 1 3]
 [3 9 6 8 0 9 8 9 7 0]]
[1 2 2 3 4 4 5 5 8 8]
[0 1 3 4 5 5 6 6 7 9]
[0 1 1 1 3 3 5 6 8 9]
[0 0 1 2 2 2 2 3 4 7]
[0 0 1 2 3 5 8 8 9 9]
[0 1 1 2 3 5 6 7 8 9]
[0 1 2 3 4 6 7 9 9 9]
[0 1 2 3 4 6 6 6 7 8]
[1 1 1 1 3 5 5 6 7 8]
[0 0 3 6 7 8 8 9 9 9]
0:00:00.008010
[1 2 2 3 4 4 5 5 8 8]
[0 1 3 4 5 5 6 6 7 9]
[0 1 1 1 3 3 5 6 8 9]
[0 0 1 2 2 2 2 3 4 7]
[0 0 1 2 3 5 8 8 9 9]
[0 1 1 2 3 5 6 7 8 9]
[0 1 2 3 4 6 7 9 9 9]
[0 1 2 3 4 6 6 6 7 8]
[1 1 1 1 3 5 5 6 7 8]
[0 0 3 6 7 8 8 9 9 9]
0:00:00.004521
[1 2 2 3 4 4 5 5 8 8]
[0 1 3 4 5 5 6 6 7 9]
[0 1 1 1 3 3 5 6 8 9]
[0 0 1 2 2 2 2 3 4 7]
[0 0 1 2 3 5 8 8 9 9]
[0 1 1 2 3 5 6 7 8 9]
[0 1 2 3 4 6 7 9 9 9]
[0 1 2 3 4 6 6 6 7 8]
[1 1 1 1 3 5 5 6 7 8]
[0 0 3 6 7 8 8 9 9 9]
0:00:00
[1 2 2 3 4 4 5 5 8 8]
[0 1 3 4 5 5 6 6 7 9]
[0 1 1 1 3 3 5 6

In [51]:
from datetime import datetime
import random
import copy

def test_sort(matr, func, namesort):
    
    start_time = datetime.now()
    
    for i in range(len(matr)):
        func(matr[i])

    end_time = datetime.now()

    print(namesort)
    print(end_time - start_time)
    
    for i in range(len(matr) - 1):
        print(matr[i])


# Выбором
def selection_sort(alist):
    for i in range(0, len(alist) - 1):
        smallest = i
        for j in range(i + 1, len(alist)):
            if alist[j] < alist[smallest]:
                smallest = j
        alist[i], alist[smallest] = alist[smallest], alist[i]

# Вставкой
def insertion_sort(alist):
    for i in range(1, len(alist)):
        temp = alist[i]
        j = i - 1
        while (j >= 0 and temp < alist[j]):
            alist[j + 1] = alist[j]
            j = j - 1
        alist[j + 1] = temp
        
# Обменом
def bubble_sort(alist):
    for i in range(len(alist) - 1, 0, -1):
        no_swap = True
        for j in range(0, i):
            if alist[j + 1] < alist[j]:
                alist[j], alist[j + 1] = alist[j + 1], alist[j]
                no_swap = False
        if no_swap:
            return

# Шелла
def shell(data):
    inc = len(data) // 2
    while inc:
        for i, el in enumerate(data):
            while i >= inc and data[i - inc] > el:
                data[i] = data[i - inc]
                i -= inc
            data[i] = el
        inc = 1 if inc == 2 else int(inc * 5.0 / 11)
    return data

# Быстрая сортировка
def quicksort(alist, start = -1, end = -1):
    start = 0 if start == -1 else start
    end = len(alist) if end == -1 else end
    if end - start > 1:
        p = partition(alist, start, end)
        quicksort(alist, start, p)
        quicksort(alist, p + 1, end)
 
 
def partition(alist, start, end):
    pivot = alist[start]
    i = start + 1
    j = end - 1
 
    while True:
        while (i <= j and alist[i] <= pivot):
            i = i + 1
        while (i <= j and alist[j] >= pivot):
            j = j - 1
 
        if i <= j:
            alist[i], alist[j] = alist[j], alist[i]
        else:
            alist[start], alist[j] = alist[j], alist[start]
            return j

# Турнирная
def heapsort(alist):
    build_max_heap(alist)
    for i in range(len(alist) - 1, 0, -1):
        alist[0], alist[i] = alist[i], alist[0]
        max_heapify(alist, index=0, size=i)
 
def parent(i):
    return (i - 1)//2
 
def left(i):
    return 2*i + 1
 
def right(i):
    return 2*i + 2
 
def build_max_heap(alist):
    length = len(alist)
    start = parent(length - 1)
    while start >= 0:
        max_heapify(alist, index=start, size=length)
        start = start - 1
 
def max_heapify(alist, index, size):
    l = left(index)
    r = right(index)
    if (l < size and alist[l] > alist[index]):
        largest = l
    else:
        largest = index
    if (r < size and alist[r] > alist[largest]):
        largest = r
    if (largest != index):
        alist[largest], alist[index] = alist[index], alist[largest]
        max_heapify(alist, largest, size)
        
# Основная программа
m = int(input("Enter the m (50 - default value) : ") or "50")
n = int(input("Enter the n (50 - default value) : ") or "50")
min_lim = int(input("Enter the min_limit (-250 - default value) : ") or "-250")
max_lim = int(input("Enter the max_limit (1002 - default value) : ") or "1002")
matr = [[random.randint(min_lim, max_lim) for j in range(m)] for i in range(n)]
#print(matr)

test_sort(copy.deepcopy(matr), list.sort, "Standart:")
test_sort(copy.deepcopy(matr), selection_sort, "Selection:")
test_sort(copy.deepcopy(matr), insertion_sort, "Insertion:")
test_sort(copy.deepcopy(matr), shell, "Shell:")
test_sort(copy.deepcopy(matr), quicksort, "Quick:")
test_sort(copy.deepcopy(matr), heapsort, "Pyramid:")


Enter the m (50 - default value) : 10
Enter the n (50 - default value) : 3
Enter the min_limit (-250 - default value) : 0
Enter the max_limit (1002 - default value) : 8
Standart:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
Selection:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
Insertion:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
Shell:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
Quick:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
Pyramid:
0:00:00
[0, 0, 0, 1, 1, 1, 7, 7, 8, 8]
[2, 2, 3, 4, 4, 5, 6, 7, 8, 8]
